### ISSUE TITLE
Test case failed with EI 6.2.0

### ISSUE THREAD

**Issue by Biruntha** [wso2-extensions/esb-connector-googledriverest#13]
**Description:**
Test case failed with EI 6.2.0
Tests run: 59, Failures: 3, Errors: 0, Skipped: 1, Time elapsed: 202.752 sec <<< FAILURE!
testInsertPermissionWithMandatoryParameters(org.wso2.carbon.connector.integration.test.googledriverest.GoogledriveRestConnectorIntegrationTest)  Time elapsed: 0.841 sec  <<< FAILURE!
java.lang.AssertionError: expected:<200> but was:<400>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:365)
	at org.testng.Assert.assertEquals(Assert.java:375)
	at org.wso2.carbon.connector.integration.test.googledriverest.GoogledriveRestConnectorIntegrationTest.testInsertPermissionWithMandatoryParameters(GoogledriveRestConnectorIntegrationTest.java:810)

testUpdatePermissionWithMandatoryParameters(org.wso2.carbon.connector.integration.test.googledriverest.GoogledriveRestConnectorIntegrationTest)  Time elapsed: 1.329 sec  <<< FAILURE!
org.json.JSONException: JSONObject["kind"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at org.json.JSONObject.getString(JSONObject.java:669)
	at org.wso2.carbon.connector.integration.test.googledriverest.GoogledriveRestConnectorIntegrationTest.testUpdatePermissionWithMandatoryParameters(GoogledriveRestConnectorIntegrationTest.java:719)

testGetRealTimeWithMandatoryParameters(org.wso2.carbon.connector.integration.test.googledriverest.GoogledriveRestConnectorIntegrationTest)  Time elapsed: 0.838 sec  <<< FAILURE!
java.lang.AssertionError: expected:<200> but was:<403>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:365)
	at org.testng.Assert.assertEquals(Assert.java:375)
	at org.wso2.carbon.connector.integration.test.googledriverest.GoogledriveRestConnectorIntegrationTest.testGetRealTimeWithMandatoryParameters(GoogledriveRestConnectorIntegrationTest.java:1081)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Biruntha** [comment]
Integration test is automated with this PR[1].

[1] https://github.com/wso2-extensions/esb-connector-googledriverest/pull/15
